"use strict";
exports.__esModule = true;
var vehiculo_1 = require("./vehiculo");
var vehiculoCamion_1 = require("./vehiculoCamion");
var vehiculoMoto_1 = require("./vehiculoMoto");
var registroAutomotor_1 = require("./registroAutomotor");
var registro = new registroAutomotor_1.RegistroAutomotor;
registro.altaAuto(new vehiculo_1.Vehiculo(false, false, 5));
registro.altaAuto(new vehiculo_1.Vehiculo(true, false, 2));
registro.altaAuto(new vehiculo_1.Vehiculo(false, true, 1));
registro.altaAuto(new vehiculo_1.Vehiculo(false, false, 5));
registro.altaCamion(new vehiculoCamion_1.Camion(false, false, 1, true));
registro.altaCamion(new vehiculoCamion_1.Camion(true, false, 0, false));
registro.altaCamion(new vehiculoCamion_1.Camion(false, true, 2, false));
registro.altaCamion(new vehiculoCamion_1.Camion(true, false, 1, true));
registro.altaMoto(new vehiculoMoto_1.Moto(false, false, 1, true));
registro.altaMoto(new vehiculoMoto_1.Moto(false, true, 0, false));
registro.altaMoto(new vehiculoMoto_1.Moto(true, false, 3, false));
registro.altaMoto(new vehiculoMoto_1.Moto(false, true, 2, true));
registro.consultarTodos();
